
# This is the main configuration file for Supabase CLI
project_id = "vngmjjvfofoggfqgpizo"

[api]
port = 54321
schemes = ["http", "https"]
version = 1

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "https://app.example.com"
additional_redirect_urls = ["https://example.com"]
jwt_expiry = 3600
enable_signup = true

[functions]
[functions.traceability-notifications]
verify_jwt = true
[functions.recall-schedule-processor]
verify_jwt = false

[realtime]
enabled = true
