
# This file defines Supabase project configuration

project_id = "vngmjjvfofoggfqgpizo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.document-approval]
verify_jwt = true
